export type VenueId = string;

export type VenueCategory = 
  | 'tier1_derivatives' 
  | 'tier1_spot' 
  | 'dex_l1' 
  | 'institutional_broker' 
  | 'regional_regulated';

export type AuthType = 'api_keys' | 'web3_agent' | 'oauth_token' | 'fix_session' | 'terminal_bridge';

export interface StoredExchangeAccount {
  id: string;
  venueId: string;
  venueName: string;
  label: string;
  authType: AuthType;
  apiKey: string;
  apiSecret: string;
  passphrase?: string;
  agentAddress?: string;
  isTestnet: boolean;
  subaccountName?: string;
  permissions: ('read' | 'trade')[];
  status: 'CONNECTED' | 'ERROR' | 'STANDBY';
  balanceUsd: number;
  freeMarginUsd: number;
  pingMs: number;
  lastSync: string;
  createdAt: string;
}

export interface VenueMetadata {
  id: string;
  name: string;
  tagline: string;
  category: VenueCategory;
  color: string;
  authType: AuthType;
  requiresPassphrase: boolean;
  supportsOAuth?: boolean;
  supportsTestnet: boolean;
  supportsPerpetuals: boolean;
  supportsSpot: boolean;
  rateLimitInfo: string;
  ccxtId: string;
  documentationUrl: string;
  isFavoriteDefault?: boolean;
}

export const SUPPORTED_VENUES: VenueMetadata[] = [
  // --- TIER 1 DERIVATIVES & CRYPTO PERPETUALS (CCXT PRIMARY) ---
  {
    id: 'binance',
    name: 'Binance Global',
    tagline: 'Spot & USDⓈ-M / COIN-M Futures con routing institucional',
    category: 'tier1_derivatives',
    color: '#F0B90B',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: true,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '1200 weight/min',
    ccxtId: 'binance',
    documentationUrl: 'https://binance-docs.github.io/apidocs/futures/en/',
    isFavoriteDefault: true
  },
  {
    id: 'bybit',
    name: 'Bybit Unified V5',
    tagline: 'Perpetuals, Inversos & Spot via Unified Trading Account',
    category: 'tier1_derivatives',
    color: '#F7A600',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '50 req/s',
    ccxtId: 'bybit',
    documentationUrl: 'https://bybit-exchange.github.io/docs/v5/intro',
    isFavoriteDefault: true
  },
  {
    id: 'okx',
    name: 'OKX DMA Unified',
    tagline: 'Direct Market Access con cuenta unificada multimoneda',
    category: 'tier1_derivatives',
    color: '#FFFFFF',
    authType: 'api_keys',
    requiresPassphrase: true,
    supportsOAuth: true,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '20 req/2s',
    ccxtId: 'okx',
    documentationUrl: 'https://www.okx.com/docs-v5/en/',
    isFavoriteDefault: true
  },
  {
    id: 'kucoin',
    name: 'KuCoin Futures',
    tagline: 'Spot y Contratos Perpetuos USDT-M / COIN-M con Level 3 Data',
    category: 'tier1_derivatives',
    color: '#24AE8F',
    authType: 'api_keys',
    requiresPassphrase: true,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '1800 req/min',
    ccxtId: 'kucoin',
    documentationUrl: 'https://www.kucoin.com/docs/rest/futures-trading',
    isFavoriteDefault: true
  },
  {
    id: 'bitget',
    name: 'Bitget Unified',
    tagline: 'Cuentas de derivados USDT-M/USDC-M y Copy Trading API',
    category: 'tier1_derivatives',
    color: '#00F0FF',
    authType: 'api_keys',
    requiresPassphrase: true,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '20 req/s',
    ccxtId: 'bitget',
    documentationUrl: 'https://www.bitget.com/api-doc/common/intro',
    isFavoriteDefault: true
  },
  {
    id: 'gateio',
    name: 'Gate.io Delivery & Perp',
    tagline: 'Perpetuos, Opciones y Margen cruzado multiactivo',
    category: 'tier1_derivatives',
    color: '#E04B4B',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '300 req/s',
    ccxtId: 'gateio',
    documentationUrl: 'https://www.gate.io/docs/developers/apiv4/'
  },
  {
    id: 'deribit',
    name: 'Deribit Institutional',
    tagline: 'Estándar global en Opciones BTC/ETH y Futuros inversos',
    category: 'tier1_derivatives',
    color: '#00B2A9',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: false,
    rateLimitInfo: '20 req/s',
    ccxtId: 'deribit',
    documentationUrl: 'https://docs.deribit.com/',
    isFavoriteDefault: true
  },
  {
    id: 'mexc',
    name: 'MEXC Global',
    tagline: 'Spreads ajustados en futuros perp y listing continuo',
    category: 'tier1_derivatives',
    color: '#2862FF',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '20 req/s',
    ccxtId: 'mexc',
    documentationUrl: 'https://mexcdevelop.github.io/apidocs/'
  },
  {
    id: 'htx',
    name: 'HTX (Huobi)',
    tagline: 'Derivados de futuros USDT y cuenta de trading unificada',
    category: 'tier1_derivatives',
    color: '#0066ED',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '100 req/2s',
    ccxtId: 'huobi',
    documentationUrl: 'https://www.htx.com/en-us/opendocument'
  },
  {
    id: 'bingx',
    name: 'BingX Pro',
    tagline: 'Standard & Perpetual Futures con soporte Copy Trading API',
    category: 'tier1_derivatives',
    color: '#2354E6',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '10 req/s',
    ccxtId: 'bingx',
    documentationUrl: 'https://bingx-api.github.io/docs/'
  },
  {
    id: 'phemex',
    name: 'Phemex Unified',
    tagline: 'Contratos con colateral multimoneda y latencia sub-milisegundo',
    category: 'tier1_derivatives',
    color: '#E5A93C',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '500 req/min',
    ccxtId: 'phemex',
    documentationUrl: 'https://phemex-docs.github.io/'
  },
  {
    id: 'bitmex',
    name: 'BitMEX Perpetual',
    tagline: 'Pionero en Swap Perpetuo BTC/USD y contratos cuánticos',
    category: 'tier1_derivatives',
    color: '#ED1B24',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '60 req/min',
    ccxtId: 'bitmex',
    documentationUrl: 'https://www.bitmex.com/app/apiOverview'
  },
  {
    id: 'woo',
    name: 'WOO X Network',
    tagline: 'Profundidad de liquidez institucional con zero-fee staking',
    category: 'tier1_derivatives',
    color: '#00E19B',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '10 req/s',
    ccxtId: 'woo',
    documentationUrl: 'https://docs.woo.org/'
  },
  {
    id: 'bitfinex',
    name: 'Bitfinex Margin & Derivatives',
    tagline: 'Libros profundos institucionales y WebSocket v2 optimizado',
    category: 'tier1_derivatives',
    color: '#14C882',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '90 req/min',
    ccxtId: 'bitfinex',
    documentationUrl: 'https://docs.bitfinex.com/'
  },
  {
    id: 'coinex',
    name: 'CoinEx Futures',
    tagline: 'Trading continuo de perpetuos y swap automatizado',
    category: 'tier1_derivatives',
    color: '#00C988',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '20 req/s',
    ccxtId: 'coinex',
    documentationUrl: 'https://docs.coinex.com/'
  },
  {
    id: 'lbank',
    name: 'LBank Futures',
    tagline: 'Contratos USDT con liquidación en tiempo real',
    category: 'tier1_derivatives',
    color: '#FFB800',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '20 req/s',
    ccxtId: 'lbank',
    documentationUrl: 'https://www.lbank.com/en-US/docs/index.html'
  },
  {
    id: 'ascendex',
    name: 'AscendEX Futures',
    tagline: 'Margen cruzado y perpetuos de alta volatilidad',
    category: 'tier1_derivatives',
    color: '#E9523C',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '100 req/s',
    ccxtId: 'ascendex',
    documentationUrl: 'https://ascendex.github.io/ascendex-pro-api/'
  },
  {
    id: 'blofin',
    name: 'Blofin Futures',
    tagline: 'Perpetuos descentralizados y CeFi de baja latencia',
    category: 'tier1_derivatives',
    color: '#0066FF',
    authType: 'api_keys',
    requiresPassphrase: true,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '20 req/s',
    ccxtId: 'blofin',
    documentationUrl: 'https://blofin.com/docs'
  },
  {
    id: 'zoomex',
    name: 'Zoomex Derivatives',
    tagline: 'Trading anónimo de futuros con infraestructura de liquidez Bybit',
    category: 'tier1_derivatives',
    color: '#10B981',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: false,
    rateLimitInfo: '30 req/s',
    ccxtId: 'zoomex',
    documentationUrl: 'https://help.zoomex.com/'
  },

  // --- DEXs L1 & HIGH-SPEED ON-CHAIN ORDER BOOKS ---
  {
    id: 'hyperliquid',
    name: 'Hyperliquid L1',
    tagline: 'DEX L1 nativo con libro de órdenes on-chain y latencia sub-milisegundo',
    category: 'dex_l1',
    color: '#2DD4BF',
    authType: 'web3_agent',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '1200 req/min via L1 Tendermint',
    ccxtId: 'hyperliquid',
    documentationUrl: 'https://hyperliquid.gitbook.io/hyperliquid-docs',
    isFavoriteDefault: true
  },
  {
    id: 'dydx',
    name: 'dYdX Chain v4',
    tagline: 'App-chain Cosmos soberana con libro de órdenes descentralizado',
    category: 'dex_l1',
    color: '#6966FF',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: false,
    rateLimitInfo: '100 req/s WebSocket',
    ccxtId: 'dydx',
    documentationUrl: 'https://docs.dydx.exchange/'
  },
  {
    id: 'vertex',
    name: 'Vertex Protocol',
    tagline: 'Motor de casamiento cruzado híbrido DEX en Arbitrum L2',
    category: 'dex_l1',
    color: '#8B5CF6',
    authType: 'web3_agent',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'Edge Engine 15ms',
    ccxtId: 'vertex',
    documentationUrl: 'https://vertex-protocol.gitbook.io/docs/'
  },
  {
    id: 'aevo',
    name: 'Aevo L2 Rollup',
    tagline: 'Rollup OP Stack especializado en Opciones y Perpetuos descentralizados',
    category: 'dex_l1',
    color: '#E11D48',
    authType: 'web3_agent',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: false,
    rateLimitInfo: 'Sequencer 10ms',
    ccxtId: 'aevo',
    documentationUrl: 'https://docs.aevo.xyz/'
  },
  {
    id: 'paradex',
    name: 'Paradex Starknet L2',
    tagline: 'Orderbook de derivados de alta velocidad basado en ZK-STARKs',
    category: 'dex_l1',
    color: '#06B6D4',
    authType: 'web3_agent',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: false,
    rateLimitInfo: 'Bantam ZK Engine',
    ccxtId: 'paradex',
    documentationUrl: 'https://docs.paradex.trade/'
  },
  {
    id: 'apexpro',
    name: 'ApeX Pro Omni',
    tagline: 'Perpetuos StarkEx multichain con comisiones taker mínimas',
    category: 'dex_l1',
    color: '#3B82F6',
    authType: 'web3_agent',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: false,
    rateLimitInfo: 'StarkEx 20 req/s',
    ccxtId: 'apexpro',
    documentationUrl: 'https://apexpro.gitbook.io/'
  },
  {
    id: 'drift',
    name: 'Drift Protocol',
    tagline: 'DEX de perpetuos de baja latencia construido en Solana',
    category: 'dex_l1',
    color: '#9333EA',
    authType: 'web3_agent',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'Solana TPS',
    ccxtId: 'drift',
    documentationUrl: 'https://docs.drift.trade/'
  },
  {
    id: 'gmx',
    name: 'GMX v2 Synthetic',
    tagline: 'Mercados sintéticos de perpetuos con oráculo Chainlink en Arbitrum',
    category: 'dex_l1',
    color: '#2563EB',
    authType: 'web3_agent',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'Arbitrum RPC',
    ccxtId: 'gmx',
    documentationUrl: 'https://gmx-io.gitbook.io/gmx/'
  },

  // --- REGIONAL, REGULATED & TIER 1 SPOT VENUES ---
  {
    id: 'coinbase',
    name: 'Coinbase Advanced',
    tagline: 'Pasarela regulada estadounidense con liquidez institucional',
    category: 'regional_regulated',
    color: '#0052FF',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: true,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '30 req/s',
    ccxtId: 'coinbase',
    documentationUrl: 'https://docs.cdp.coinbase.com/advanced-trade/docs/welcome',
    isFavoriteDefault: true
  },
  {
    id: 'kraken',
    name: 'Kraken Institutional',
    tagline: 'Futuros regulados FCA/FinCEN y Spot con Nivel 3 de profundidad',
    category: 'regional_regulated',
    color: '#5741D9',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'Rate tier dependiente',
    ccxtId: 'kraken',
    documentationUrl: 'https://docs.kraken.com/api/',
    isFavoriteDefault: true
  },
  {
    id: 'bitstamp',
    name: 'Bitstamp Europe',
    tagline: 'Licencia bancaria europea MiFID II y conexión FIX de ultra-baja latencia',
    category: 'regional_regulated',
    color: '#00A859',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: false,
    supportsSpot: true,
    rateLimitInfo: '600 req/10min',
    ccxtId: 'bitstamp',
    documentationUrl: 'https://www.bitstamp.net/api/'
  },
  {
    id: 'gemini',
    name: 'Gemini Institutional',
    tagline: 'Custodia fiduciaria NYDFS y libros de subasta regulada',
    category: 'regional_regulated',
    color: '#00DCFA',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '600 req/min',
    ccxtId: 'gemini',
    documentationUrl: 'https://docs.gemini.com/rest-api/'
  },
  {
    id: 'whitebit',
    name: 'WhiteBIT Europe',
    tagline: 'Exchange regulado en UE con pares fiat EUR/USD y derivados',
    category: 'regional_regulated',
    color: '#F472B6',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '100 req/s',
    ccxtId: 'whitebit',
    documentationUrl: 'https://whitebit-exchange.github.io/api-docs/'
  },
  {
    id: 'cryptocom',
    name: 'Crypto.com Exchange',
    tagline: 'Licencia VARA/MAS y motor OMS institucional OMSv2',
    category: 'regional_regulated',
    color: '#002D74',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '100 req/s',
    ccxtId: 'cryptocom',
    documentationUrl: 'https://exchange-docs.crypto.com/'
  },
  {
    id: 'upbit',
    name: 'Upbit Korea',
    tagline: 'Líder en volumen spot de Corea del Sur (KRW pairs)',
    category: 'regional_regulated',
    color: '#093687',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: false,
    supportsSpot: true,
    rateLimitInfo: '30 req/s',
    ccxtId: 'upbit',
    documentationUrl: 'https://docs.upbit.com/'
  },
  {
    id: 'bithumb',
    name: 'Bithumb Global',
    tagline: 'Volumen spot fiat coreano con API v2',
    category: 'regional_regulated',
    color: '#F37321',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: false,
    supportsSpot: true,
    rateLimitInfo: '10 req/s',
    ccxtId: 'bithumb',
    documentationUrl: 'https://api.bithumb.com/'
  },
  {
    id: 'bitso',
    name: 'Bitso LATAM',
    tagline: 'Principal rampa fiat cripto en México, Brasil y Colombia',
    category: 'regional_regulated',
    color: '#00E885',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: false,
    supportsSpot: true,
    rateLimitInfo: '300 req/min',
    ccxtId: 'bitso',
    documentationUrl: 'https://bitso.com/api_info'
  },
  {
    id: 'mercadobitcoin',
    name: 'Mercado Bitcoin',
    tagline: 'Líder regulado en Brasil para pares BRL y activos tokenizados',
    category: 'regional_regulated',
    color: '#F7931A',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: false,
    supportsSpot: true,
    rateLimitInfo: '100 req/min',
    ccxtId: 'mercadobitcoin',
    documentationUrl: 'https://api.mercadobitcoin.net/'
  },
  {
    id: 'bitvavo',
    name: 'Bitvavo Netherlands',
    tagline: 'Pasarela europea con registro ante el Banco Central Holandés',
    category: 'regional_regulated',
    color: '#0062FF',
    authType: 'api_keys',
    requiresPassphrase: false,
    supportsOAuth: false,
    supportsTestnet: false,
    supportsPerpetuals: false,
    supportsSpot: true,
    rateLimitInfo: '1000 weight/min',
    ccxtId: 'bitvavo',
    documentationUrl: 'https://docs.bitvavo.com/'
  },

  // --- INSTITUTIONAL DMA BROKERS, FOREX & PROTOCOLS ---
  {
    id: 'metatrader5',
    name: 'MetaTrader 5 Terminal',
    tagline: 'Conexión DMA ZeroMQ/IPC con terminales de Prop Firms y Brokers ECN',
    category: 'institutional_broker',
    color: '#22C55E',
    authType: 'terminal_bridge',
    requiresPassphrase: true,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'Sub-millisecond IPC',
    ccxtId: 'mt5',
    documentationUrl: 'https://www.mql5.com/en/docs',
    isFavoriteDefault: true
  },
  {
    id: 'ctrader',
    name: 'cTrader Open API',
    tagline: 'Conexión nativa Protobuf en Spotware Cloud para trading interbancario',
    category: 'institutional_broker',
    color: '#06B6D4',
    authType: 'oauth_token',
    requiresPassphrase: false,
    supportsOAuth: true,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'TCP Protobuf 50 msg/s',
    ccxtId: 'ctrader',
    documentationUrl: 'https://openapi.ctrader.com/',
    isFavoriteDefault: true
  },
  {
    id: 'metatrader4',
    name: 'MetaTrader 4 Bridge',
    tagline: 'Puente TCP con servidores ECN/STP de prop firms tradicionales',
    category: 'institutional_broker',
    color: '#F59E0B',
    authType: 'terminal_bridge',
    requiresPassphrase: true,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'Local Socket Bridge',
    ccxtId: 'mt4',
    documentationUrl: 'https://book.mql4.com/'
  },
  {
    id: 'quickfix',
    name: 'QuickFIX DMA Gateway',
    tagline: 'Protocolo FIX 4.4 / 5.0 institucional para Prime Brokers y Liquidity Pools',
    category: 'institutional_broker',
    color: '#6366F1',
    authType: 'fix_session',
    requiresPassphrase: true,
    supportsOAuth: false,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'Sub-millisecond FIX Protocol',
    ccxtId: 'quickfix',
    documentationUrl: 'https://www.quickfixengine.org/'
  },
  {
    id: 'interactivebrokers',
    name: 'Interactive Brokers TWS',
    tagline: 'Conectividad directa TWS API para acciones, futuros CME y opciones',
    category: 'institutional_broker',
    color: '#D92D20',
    authType: 'oauth_token',
    requiresPassphrase: false,
    supportsOAuth: true,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: '50 msg/s TWS API',
    ccxtId: 'ib',
    documentationUrl: 'https://interactivebrokers.github.io/'
  },
  {
    id: 'pepperstone',
    name: 'Pepperstone ECN Direct',
    tagline: 'Acceso directo a liquidez bancaria interbancaria cTrader/FIX',
    category: 'institutional_broker',
    color: '#E11D48',
    authType: 'oauth_token',
    requiresPassphrase: false,
    supportsOAuth: true,
    supportsTestnet: true,
    supportsPerpetuals: true,
    supportsSpot: true,
    rateLimitInfo: 'FIX / Protobuf API',
    ccxtId: 'pepperstone',
    documentationUrl: 'https://pepperstone.com/'
  }
];
